name: PR Workflow
on: pull_request

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Run build script
        run: echo "Hello World" 
        shell: bash
